import { Food } from './Food';
import { Tag } from './Tag';

export const FOODS: Food[] = [
  {
    id: '1',
    name: 'Pizza',
    price: 10,
    tags: ['Fast Food', 'Italian'],
    favourite: true,
    stars: 4.5,
    imageUrl: 'assets/images/food-1.jpg',
    origins: ['Italy'],
    cookTime: '30-40 minutes',
  },
  {
    id: '2',
    name: 'Burger',
    price: 5,
    tags: ['Fast Food', 'American', 'Burger'],
    favourite: false,
    stars: 4.0,
    imageUrl: 'assets/images/food-2.jpg',
    origins: ['USA'],
    cookTime: '15-20 minutes',
  },
  {
    id: '3',
    name: 'Pizza',
    price: 10,
    tags: ['FastFood', 'Italian', 'Pizza'],
    favourite: true,
    stars: 4.5,
    imageUrl: 'assets/images/food-1.jpg',
    origins: ['Italy'],
    cookTime: '30-40 minutes',
  },
  {
    id: '4',
    name: 'Burger',
    price: 5,
    tags: ['FastFood', 'American', 'Burger'],
    favourite: false,
    stars: 4.0,
    imageUrl: 'assets/images/food-2.jpg',
    origins: ['USA'],
    cookTime: '15-20 minutes',
  },
  {
    id: '5',
    name: 'Pizza',
    price: 10,
    tags: ['Fast Food', 'Italian', 'Pizza'],
    favourite: true,
    stars: 4.5,
    imageUrl: 'assets/images/food-1.jpg',
    origins: ['Italy'],
    cookTime: '30-40 minutes',
  },
  {
    id: '6',
    name: 'Vegetable Pizza',
    price: 5,
    tags: ['FastFood', 'Pizza', 'Lunch'],
    favourite: false,
    stars: 4.0,
    imageUrl: 'assets/images/food-5.jpg',
    origins: ['USA'],
    cookTime: '15-20 minutes',
  },
];

export const sample_tags: Tag[] = [
  { name: 'All', count: 6 },
  { name: 'Pizza', count: 6 },
  { name: 'Burger', count: 4 },
  { name: 'Fries', count: 5 },
  { name: 'ColdDrink', count: 6 },
];
